<?php

return [
    'title' => 'Recruitment in Polish medical From doctors, dentists, nurses, for doctors, dentists, nurses.',
    'description' => 'The current situation has resulted in many years of neglect in health care in Poland.<br><br>As an innovative portal, we focus on transparency, and our mission has always been to help the Polish medical industry find a better job as well as a medical facility to fill staff shortages.<br><br>Advertisements on portals are one thing, but our goal is to gather information about who recruits throughout the Polish medical market in one place - so let me know what it looks like in your company right now via the form below.<br><br>Let\'s help everyone who is currently looking for a job.#EmployMed.eu',
    'situation' => 'What is recruitment in your company like?',
    'footer-info' => 'From medics to medics - a board generated by users',
    'status' => 'Status',
    'link' => 'Link to recruitment',
    'employs' => 'Employs',
    'waiting' => 'Waiting',
    'releases' => 'Releases',
    'store-success' => 'Thank you for adding information, take care and be healthy.'
];
