<?php

return [
    'title' => 'Recruitment in the Polish medical industry. From doctors, dentists, nurses, for doctors, dentists, nurses.',
    'description' => 'The current epidemiad has clearly shown that the Polish health care system is a colossus on clay legs.<br><br>As an innovative portal, we focus primarily on transparency. From the beginning, our mission has been to help connect medical personnel looking for work with institutions.<br><br>Advertisements on portals are one thing, but our goal is also to follow trends in the medical labor market and follow them.<br><br>We want you ask for anonymous opinion on the situation in your workplace directly via the form below.<br><br>After the end of the epidemic, we plan to create a report on the employment status of doctors and dentists in our country. #EmployMed.eu',
    'situation' => 'What is recruitment in your company like?',
    'footer-info' => 'From medics to medics - a board generated by users',
    'status' => 'Status',
    'link' => 'Link to recruitment',
    'employs' => 'Employs',
    'waiting' => 'Waiting',
    'releases' => 'Releases',
    'store-success' => 'Thank you for adding information, take care and be healthy.'
];
